### ISSUE TITLE
删除发布过文章的用户导致主题端报错

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/theme-earth#18]
### 现状
`用户A`编辑发布过若干文章，当其他管理员把`用户A`删除后，会导致这些文章没有作者，进而导致主题模板解析时出错。
```
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "/root/halo-next/themes/theme-earth/templates/index.html")
        at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241) ~[thymeleaf-3.1.0.RC1.jar:3.1.0.RC1]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ Handler run.halo.app.theme.router.strategy.IndexRouteStrategy$$Lambda$1185/0x000000080122fad0@7f02e477 [DispatcherHandler]
        *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241) ~[thymeleaf-3.1.0.RC1.jar:3.1.0.RC1]
                at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100) ~[thymeleaf-3.1.0.RC1.jar:3.1.0.RC1]
                at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:666) ~[thymeleaf-3.1.0.RC1.jar:3.1.0.RC1]
                at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.RC1.jar:3.1.0.RC1]
                at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.RC1.jar:3.1.0.RC1]
                at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:2.0.0-beta.1]
                at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
                at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
                at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "post.contributors[0]" (template: "modules/post-card" - line 60, col 68)
```

### 期望
1. 主题端进行优化，当文章没有作者时仍可以正常解析；
2. 后端进行优化，避免出现无作者的文章。

**Comment by ruibaby** [comment]
/cc @guqing 

这个需要按照我们上次说的，需要提供 owner 给到 Post。Contributors 应该是不确定的，即便要显示，那么应该是遍历，就不会出现这样的问题。
